language: java
jdk: oraclejdk8
sudo: true
env:
  - MAVEN_REPOSITORY=$HOME/.m2/repository
before_install:
  #- sudo jdk_switcher use oraclejdk8
  #- sudo java -Xmx32m -version
  - ls -l /usr/lib/jvm/java-8-oracle/jre/lib/rt.jar
  - env
  - ls
  - ls -l bin
  - which mvn
  - ./bin/prepare-jvm.sh
  - sudo rm /usr/lib/jvm/java-6-openjdk-amd64/jre/lib/rt.jar
  - sudo rm /usr/lib/jvm/java-7-oracle/jre/lib/rt.jar
  - sudo rm /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/rt.jar
  - wget http://varaneckas.com/jad/jad158e.linux.static.zip
  - unzip jad158e.linux.static.zip
  - mkdir rt
  - unzip -q /usr/lib/jvm/java-8-oracle/jre/lib/rt.jar -d rt
  - ./jad rt/java/lang/String.class
  - cat String.jad
  - pushd .
  - cd /
  - sudo find -name rt.jar
  - popd
  - rm -rf $HOME/.cache
  - mvn dependency:purge-local-repository -DactTransitively=false -DreResolve=false
  - sudo rm /usr/lib/jvm/java-8-oracle/jre/lib/rt.jar
#  - mkdir ./before_install
#  - mvn dependency:resolve
#  - 'sudo $JAVA_HOME/bin/javac -classpath "$MAVEN_REPOSITORY/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar:$MAVEN_REPOSITORY/com/google/guava/guava/18.0/guava-18.0.jar"
#           -d ./before_install
#           $TRAVIS_BUILD_DIR/src/main/java/org/brandonhaynes/pipegen/utilities/JvmUtilities.java
#           $TRAVIS_BUILD_DIR/src/main/java/org/brandonhaynes/pipegen/mutation/ClassModifierReplacer.java
#           $TRAVIS_BUILD_DIR/src/main/java/org/brandonhaynes/pipegen/utilities/JarUtilities.java
#           $TRAVIS_BUILD_DIR/src/main/java/org/brandonhaynes/pipegen/configuration/Version.java
#           $TRAVIS_BUILD_DIR/src/main/java/org/brandonhaynes/pipegen/utilities/JarClassPath.java'
#  - find -name *.class
#  - 'sudo $JAVA_HOME/bin/java -classpath "./before_install:$MAVEN_REPOSITORY/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar:$MAVEN_REPOSITORY/com/google/guava/guava/18.0/guava-18.0.jar"
#          org.brandonhaynes.pipegen.utilities.JvmUtilities RemoveFinalFlagFromString java.lang.String,java.lang.StringBuilder,java.lang.StringBuffer'
#  - ls -l /usr/lib/jvm/java-8-oracle/jre/lib/rt.jar
#  - 'sudo $JAVA_HOME/jre/bin/java -classpath "./before_install:$MAVEN_REPOSITORY/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar:$MAVEN_REPOSITORY/com/google/guava/guava/18.0/guava-18.0.jar"
#          org.brandonhaynes.pipegen.utilities.JvmUtilities RemoveFinalFlagFromString java.lang.String,java.lang.StringBuilder,java.lang.StringBuffer'
#  - ls -l /usr/lib/jvm/java-8-oracle/jre/lib/rt.jar
  #./usr/lib/jvm/java-8-oracle/jre/lib/rt.jar
  #./usr/lib/jvm/java-7-openjdk-amd64/jre/lib/rt.jar
  #./usr/lib/jvm/java-6-openjdk-amd64/jre/lib/rt.jar
  #./usr/lib/jvm/java-7-oracle/jre/lib/rt.jar
